[package]
name = "mping"
version = "0.2.9"
authors = ["Mikko Tanner <mikko.tanner@gmail.com>"]
description = "Multi-pinger utility written in Rust"
readme = "README.md"
repository = "https://github.com/Ukko-Ylijumala/mping-rs"
license = "MIT OR Apache-2.0"
categories = ["network-programming"]
keywords = ["icmp", "ping", "networking", "tui", "ratatui", "async"]
publish = false
edition = "2024"
default-run = "mping"

[dependencies]
surge-ping = "0.8.3"
rand = "0.9"
futures = "0.3"
regex = "1.12"
lazy_static = "1.5"
ipnet = "2.11"
signal-hook = "0.3"
crossterm = "0.29"
ratatui = "0.30"
parking_lot = "0.12"
itertools = "0.14"
tokio-util = "0.7"
socket2 = "0.6.1"
pnet_packet = "0.35"
hickory-resolver = "0.25.2"
#tracing = "0.1"

[dependencies.tokio]
version = "1.48"
features = ["rt-multi-thread", "macros", "time", "parking_lot"]

[dependencies.clap]
version = "4.5"
features = ["cargo", "derive"]

[dependencies.reqwest]
version = "0.13.1"
features = ["blocking"]

[dependencies.miniutils]
git = "https://github.com/Ukko-Ylijumala/miniutils-rs"
version = "0.2.4"

[dependencies.timesince]
git = "https://github.com/Ukko-Ylijumala/timesince-rs"
version = "0.3.2"

[profile.release]
opt-level = 3
lto = true
# Enable to make release builds include debug info
#debug = true

[[bin]]
name = "mping"
path = "src/main.rs"

[[bin]]
name = "hopcount"
path = "src/hopcount/main.rs"

[[bin]]
name = "imploder"
path = "src/imploder/main.rs"
